// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rcxdflctnqajjkzoczlh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJjeGRmbGN0bnFhamprem9jemxoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkyMDY2NzEsImV4cCI6MjA2NDc4MjY3MX0.XhyHCVgMim1Gh4TfMCY8VU2Nxks9MIDRfykW_csyl8g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);